### ISSUE TITLE
Content pass

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#147]

**Comment by futuresoup** [comment]
## Tasks

- [ ] Update menu to Startups and Resources
- [ ] Fix syntax - font-awesome/material icons and admonitions
- [ ] Fill in Blog
- [ ] Emoji for each solution in menu bar (?)
