### ISSUE TITLE
[EPIC] - CMS improvements

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#200]
Our biggest need for a successful project is to make the writing experience better so we can facilitate a wiki style community of writers.

We are using DecapCMS ([website](https://decapcms.org/) / [GitHub](https://github.com/decaporg/decap-cms)), and it works okay, but has much to be desired, particularly for onboarding and first use of the CMS.

We can either improve DecapCMS, or explore another open source Headless CMS.

**Two options:**
Option 1: Tina CMS ([website](https://tina.io/) / [github](https://github.com/tinacms/tinacms) / [docusaurs setup guide](https://tina.io/guides/tinacms/docusaurus/guide/))

Option 2: - [Strapi](https://strapi.io/)
 
I haven't tried Tina, but it supports Git and Markdown. Need to look into self hosting. It's expensive to use their hosting service otherwise.

Strapi is much more advanced, but requires a more complex setup, I'm pretty sure the project would need to transform into a database backend setup, and I don't believe it will edit static markdown files, so that may be a dealbreaker.

## Open tickets
- [ ] #508
- [ ] #509 
- [ ] #510 
- [ ] #511  

## Potential Ideas

- [ ] Support Google Auth so people don't have to sign up for GitHub. Content writers will not have GitHub, only coders.
- [ ] Figure out a way to preview the page with it's actual formatting so the writer can see what it's going to look like
- [ ] Admonitions are available as a formatting option in the kitchen sink
- [ ] Figure out a good editorial workflow for editors to give comments to writers
- [ ] Every new page automatically starts with a styled warning that this page is a brand new work in progress, using templated [admonitions](https://docusaurus.io/docs/markdown-features/admonitions)
