### ISSUE TITLE
[EPIC] - Version 0.9 redesign - remaining tasks

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#30]
[Latest design here](https://www.figma.com/file/BnLv0mzFVOk0qrRx4TFzqr/The-Climate-Tech-Handbook).

# Highest Priority

- [ ] decide on removing sticky navigation for Table of Contents dropdown - @sbasken 
- [x] ~Convert Solutions page to solutions.md and optimize~
- [x] Get sidebar on all pages - @futuresoup 
- [x] Repo cleanup, documentation, issue migration - @futuresoup 
- [ ] Set up previous and next pages on all Solution pages - @futuresoup 
- [ ] Finish 0.9 content and stage 1.0 content draft workflow - @futuresoup 
- [x] ~Reorder social icons~
- [x] Fix sidebar emoji gap
- [x] Icon image bug is back! - @sbasken 
  - [x] Sizing - @sbasken - LinkedIn, GitHub, add Slack (chat.climatetechhandbook.com)
- [ ] Remove breadcrumbs until we figured out #220 @futuresoup 
- [x] Clean up contacts and outreach plan - @futuresoup 
- [x] ~Get meta `description:` to be automatically filled with the first few sentences in front matter. I don't believe this is happening which is messing up SEO and social media sharing. Need to confirm first though.~

---

## Content - @futuresoup 

- [x] Intro page
- [x] Career guide page
- [x] Sector descriptions
- [ ] About page (Vision, Team)
- [x] Solutions landing page
- [ ] Resources page
- [ ] Meta description for Google and link previews
- [x] Blog post
- [ ] Image card for **/sector-health-and-education**
- [ ] Test DecapCMS
- [ ] Contribute page with Patreon working
- [ ] Sweep through all Solution pages
  - [ ] Reorder by solution size and visualize with #106 and other techniques
- [ ] File ticket for role related pages
- [ ] File tickets for Level 0,1,2 content + Muxi/Fan/Neel's content
- [ ] File ticket for two new sectors - financing, data & accountability
- [ ] File routine scrub for new internal links and pages

---

## Meta

- [ ] #123 + Docusaurus repo with documentation and team announcement
- [ ] Get Figma file migrated and test + invite everybody + integrate content map JamBoard
- [ ] Update iterations, end dates, and milestones -> move tasks to v1.0 release

---

# Secondary Priority

- [x] Get social icons up
- [ ] Design for **Previous** and **Next** page navigation at the bottom of each page
- [ ] Try new Hero image
- [ ] A/B test tagline and homepage content
- [ ] File ticket for contribution video guide

### Mobile
- [x] Tighten gap between bottom of clock and image card picture so the user can see the top of the picture and knows they can scroll - @thenunachi 
- [x] Make "Next Page" and "Previous Page" far more obvious - @sbasken 
- [X] Some pages still have horizontal scroll issue
  - [X] Perhaps related to things like YouTube video too wide in /career-guide page
- [ ] ~Search bar requires manual zoom out after using~ (don't think we can fix)
- [ ] New search bar fit is still a little off. Doesn't say "search" completely, and needs to be tested on multiple screens. - @sbasken
- [x] Tighten uneven gap between Slack and the other footer icons so they're even 
- [x] See if there's room for "The" versus no "The" in the navbar. Perhaps "The" appears on Desktop but not mobile for space considerations - @thenunachi 
- [x] ~Hero fonts look small and a little weird~
- [x] ~Hero "Show me" button is too small, and should look more prominent, and perhaps more centered.~
- [x] ~Clock doesn't quite fit right still. Perhaps squeeze colons together a tad more? Ideally we could spell out "Years" instead of "Yrs" and leave the other abbreviations, which don't matter as much.~
- [x] ~Spacing gap between Job Seeker and Founders section appears to big and should be tightened.~
- [x] ~Some pages still has horizontal bouncy effect when scrolling with finger (if finger deviates sideways)~

### General
- [ ] Styling and markdown for image captions
- [x] Fix inconsistent image alignment on image cards - @sbasken 
- [x] Weird skinny fonts and sidebar text spacing on Chrome/Safari versus normal in Firefox
- [ ] Odd button width discrepancy on homepage with top "Show me" and Bottom "Find Out"
- [ ] images way to big and image cards not aligned correctly underneath for Sector pages, such as sector-transportation
- [x] Make navbar fonts larger on Desktop for legibility and accessibility
- [ ] Slightly more prominent border around "Next Page" and "Previous Page" buttons
- [x] ~Button text should be white not black~
- [X] ~Button's disappear on hover ONLY IN PRODUCTION NOT LOCALHOST~
- [ ] Line break for second sentence on "job seekers" image card so each sentence gets its own line
- [ ] Table of contents - highlight as you scroll down the page, like on the [Climate Papa post](https://www.climatepapa.com/software)

---

## Solution page & sub-pages

- [x] Fix Solution cards ([Figma Design](https://www.figma.com/file/BnLv0mzFVOk0qrRx4TFzqr/The-Climate-Tech-Handbook?type=design&node-id=507-857&mode=design&t=l9dTBEj0aoOoPOgO-0))
 - [x] Make entire card clickable, ideally with hover effect to make it more noticeable and pleasant.~
 - [ ] Content - 14 sectors and 93 solutions with image, title, and one sentence description
 - [X] ~Update arrow design~
 - [X] ~Work on arrow alignment~

## Later
- [x] Clean up front matter and file ticket for standardization
- [ ] Feedback on previous/next buttons at bottom of page, and styling
- [ ] File ticket for Algolia - @futuresoup 
- [ ] Social media previews - og:image and page description (LinkedIn, Slack, etc)
- [ ] File ticket to investigate scrunched up elements on mobile Slack App, iPhone SE newer generation ([see screenshot](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/1459051/3ecfc372-7da1-48e1-8ed7-53fd3a373194))
- [ ] File ticket for dropdown bar to filter solution cards
- [x] File ticket for menu to fade out on mobile during scroll
- [ ] Get image zoom working (turn plugin back on in docusaurus.config.js)
- [ ] File ticket to deal with displayed_sidebar problem
- [ ] DevOps - set up `develop` and `staging` branches to auto-deploy to dev and staging sites
- [x] #217
- [ ] File ticket to try Framer for landing page test and update #149 
- [ ] File ticket for making sidebar and scroll up circle a little more obvious
- [ ] File ticket to test sharing display on popular social platforms
- [ ] SEO Audit
- [ ] Audit: code quality / tech debt potential

**Comment by futuresoup** [comment]
@connor-cs this one's all you now! @ArLough is taking over the [Data Magic](https://github.com/climate-tech-handbook/data-magic/) work with our AI content generator.

**Comment by bigolboyyo** [comment]
@UlianaBil @futuresoup Is there a color palette list anywhere for our new AAA colors? So I can start adding them to my docusaurus site

**Comment by UlianaBil** [comment]
@bigolboyyo I invited you to my Figma files. Go to Homepage and you will see all the colors used on the right-side panel. If you need help with anything - let me know

**Comment by UlianaBil** [comment]
@connor-cs @bigolboyyo @ArLough @futuresoup 
Guys, after testing - the home page is ready.  if Jacob is ok with that design or wants to use some part of it.
Cards didn't work with user that well, and also the "about" section was removed as we want to focus the user on "Job seekers" and "Funders"
About the clock - it can be an animated slide, like an idea.
Please check the prototype to see an interaction ( top right corner in Figma) 
Notes are inside Figma file, next to home page

Figma file - https://www.figma.com/file/BnLv0mzFVOk0qrRx4TFzqr/The-Climate-Tech-Handbook?type=design&node-id=65%3A3&t=hiSGxqtgFHElqfup-1
