### ISSUE TITLE
[EPIC]: Second round of clean up

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#308]
[Latest design here](https://www.figma.com/file/BnLv0mzFVOk0qrRx4TFzqr/The-Climate-Tech-Handbook).

# Highest Priority

- [ ] decide on removing sticky navigation for Table of Contents dropdown - @sbasken 
- [ ] Set up previous and next pages on all Solution pages - @futuresoup 
- [ ] Finish 0.9 content and stage 1.0 content draft workflow - @futuresoup 
- [ ] Remove breadcrumbs until we figured out #220 @futuresoup 

---

## Content - @futuresoup 

- [ ] About page (Vision, Team)
- [ ] Resources page
- [ ] Meta description for Google and link previews
- [ ] Image card for **/sector-health-and-education**
- [ ] Test DecapCMS
- [ ] Contribute page with Patreon working
- [ ] Sweep through all Solution pages
  - [ ] Reorder by solution size and visualize with #106 and other techniques
- [ ] File ticket for role related pages
- [ ] File tickets for Level 0,1,2 content + Muxi/Fan/Neel's content
- [ ] File ticket for two new sectors - financing, data & accountability
- [ ] File routine scrub for new internal links and pages

---

## Meta

- [ ] #123 + Docusaurus repo with documentation and team announcement
- [ ] Get Figma file migrated and test + invite everybody + integrate content map JamBoard
- [ ] Update iterations, end dates, and milestones -> move tasks to v1.0 release

---

# Secondary Priority

- [ ] Design for **Previous** and **Next** page navigation at the bottom of each page
- [ ] Try new Hero image
- [ ] A/B test tagline and homepage content
- [ ] File ticket for contribution video guide

### General
- [ ] Styling and markdown for image captions
- [ ] Odd button width discrepancy on homepage with top "Show me" and Bottom "Find Out"
- [ ] images way to big and image cards not aligned correctly underneath for Sector pages, such as sector-transportation
- [ ] Slightly more prominent border around "Next Page" and "Previous Page" buttons
- [ ] Line break for second sentence on "job seekers" image card so each sentence gets its own line
- [ ] Table of contents - highlight as you scroll down the page, like on the [Climate Papa post](https://www.climatepapa.com/software)

---

## Solution page & sub-pages

 - [ ] Content - 14 sectors and 93 solutions with image, title, and one sentence description

## Later
- [ ] Feedback on previous/next buttons at bottom of page, and styling
- [ ] File ticket for Algolia - @futuresoup 
- [ ] Social media previews - og:image and page description (LinkedIn, Slack, etc)
- [ ] File ticket to investigate scrunched up elements on mobile Slack App, iPhone SE newer generation ([see screenshot](https://github.com/climate-tech-handbook/climate-tech-handbook/assets/1459051/3ecfc372-7da1-48e1-8ed7-53fd3a373194))
- [ ] File ticket for dropdown bar to filter solution cards
- [ ] Get image zoom working (turn plugin back on in docusaurus.config.js)
- [ ] File ticket to deal with displayed_sidebar problem
- [ ] DevOps - set up `develop` and `staging` branches to auto-deploy to dev and staging sites
- [ ] #217
- [ ] File ticket to try Framer for landing page test and update #149 
- [ ] File ticket for making sidebar and scroll up circle a little more obvious
- [ ] File ticket to test sharing display on popular social platforms
- [ ] SEO Audit
- [ ] Audit: code quality / tech debt potential
